Styling bookstore
abiy006/Bookstore-React pull request #5
Opened 2023-06-23 19:30 UTC by abiy006

Tasks accomplished on this PR:

- bootstrap is added to the style

2023-06-23 20:55 UTC, cynthiainga requested changes
Hi @abiy006, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Correct Gitflow ✔️ 
- [ ] Good commit history ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇🏾 👇🏾 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can get the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 20:55 UTC, cynthiainga commented on src/components/AddBook.js
> +      {/* </form> */}
- [ ] Please do not leave unused code as a comment in your codebase. This will make your code much noisier, It is always a good practice to keep your code clean from such comments 🙃😉

2023-06-23 20:55 UTC, cynthiainga commented on src/components/Book.js
> +      {/* <button type="button" onClick={handleRemove}>Remove</button> */}
- [ ] Please do not leave unused code as a comment in your codebase. This will make your code much noisier, It is always a good practice to keep your code clean from such comments 🙃😉
- [optional] Also for JavaScript_best_practices please delete the `console.log` that you have at line 16, it would be better to not commit `console.log` to your repo. It’s ugly, it kills performance and it can make confidential data visible to anyone using the browser tools to look at your website 🙃. If the idea was to display an error message you can display the error message in a different way.

2023-06-23 20:55 UTC, cynthiainga commented on src/components/GetBooks.js
- [optional] For JavaScript_best_practices please delete the `console.log` that you have at line 20, it would be better to not commit `console.log` to your repo. It’s ugly, it kills performance and it can make confidential data visible to anyone using the browser tools to look at your website 🙃. If the idea was to display an error message you can display the error message in a different way

2023-06-23 20:55 UTC, cynthiainga commented on src/App.css
- [ ] Good job so far on the design, but as mentioned in the project requirements your design should match the given design and you missed a lot of elements in your design.
- [ ] To find the design, [login to Zeplin](https://app.zeplin.io/login) using this credentials to login:
   -  username: `student@microverse.org`
   -  password: `jb077mL2dL0DfxJ`
   - Open the project *Bookstore CMS

Take a look at the picture below 👇🏾 👇🏾 

Your design

<img width="786" alt="Screenshot 2023-06-23 at 22 37 49" src="https://github.com/abiy006/Bookstore-React/assets/74501523/29b224dd-6d04-4fb7-9a8d-1a6b4ec1547e">

Given design

<img width="798" alt="Screenshot 2023-06-23 at 22 38 43" src="https://github.com/abiy006/Bookstore-React/assets/74501523/a40adb17-a587-4822-91a2-7c310025330c">

<img width="798" alt="Screenshot 2023-06-23 at 23 48 50" src="https://github.com/abiy006/Bookstore-React/assets/74501523/32bfcffb-15a7-49c5-af56-7407b3bb96b5">

2023-06-24 05:40 UTC, Shedrack-Sunday requested changes
Hello @abiy006     👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️  
- Nice work with the setup✔️  
  
# Required Changes  🌵 

- [ ] You made some impressive implementations which I must say is a job well done. However, there are a few  I suggest   you make In line with the requirement


_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-24 05:40 UTC, Shedrack-Sunday commented on src/App.css
- [ ] Kindly add the profile logo at the left side of the page which is missing in your design 👍 

## Your design:
![image](https://github.com/abiy006/Bookstore-React/assets/50990925/14a04d58-7940-4079-9365-c05e958aaabe)

## Template:
![image](https://github.com/abiy006/Bookstore-React/assets/50990925/2e41f53f-1e31-412e-872a-f796d123fe14)

2023-06-24 09:23 UTC, sumairq approved these changes
### Hi @abiy006  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-22 08:35 UTC, merged